spring:
  datasource:
    url: jdbc:mysql://101.43.145.108:3306/springsecurity?characterEncoding=utf-8&serverTimezone=UTC
    username: SpringSecurity
    password: l198923.
    driver-class-name: com.mysql.cj.jdbc.Driver